name: "dagster-cloud ci <command>"
description: "Run a dagster-cloud ci command"
inputs:
  command:
    required: true
    description: "The dagster-cloud ci command to run"

runs:
  using: "composite"
  steps:
    - id: ci-init
      run: $DAGSTER_CLOUD_PEX -m dagster_cloud_cli.entrypoint ci ${{ inputs.command }}
      shell: bash

