name: "Initialize CI"
description: "Parse configuration and initialize CI state"
inputs:
  project_dir:
    required: true
    description: "The root directory of the dagster project."
  deployment:
    required: false
    description: "The deployment name to deploy. This value is ignored for pull requests."
    default: "prod"

runs:
  using: "composite"
  steps:
    - name: init-env-vars
      run: >
        echo "DAGSTER_CLOUD_PEX=$GITHUB_ACTION_PATH/../../../generated/gha/dagster-cloud.pex" >> $GITHUB_ENV &&
        echo "DAGSTER_BUILD_STATEDIR=/tmp/statedir-$GITHUB_RUN_ID" >> $GITHUB_ENV
      shell: bash

    - id: ci-init
      run: $DAGSTER_CLOUD_PEX -m dagster_cloud_cli.entrypoint ci init --deployment=${{ inputs.deployment }}
      shell: bash

    - id: ci-status
      run: $DAGSTER_CLOUD_PEX -m dagster_cloud_cli.entrypoint ci status
      shell: bash

