name: 'Build and deploy dagster code locations'
description: 'Build project python executable, publish to dagster cloud, and update the code location'
inputs:
  dagster_cloud_file:
    description: 'Path to dagster_cloud.yaml'
    required: true
  python_version:
    description: 'Python version string, major.minor only, eg "3.8"'
    required: false
    default: '3.8'
  deploy:
    description: 'Whether to upload the code files and update the code location'
    required: false
    default: 'true'
  build_output_dir:
    description: 'Directory for built artifacts'
    required: false
    default: '/tmp/build'
  force_rebuild_deps:
    description: 'Whether to rebuild the dependencies, even if requirements.txt and setup.py did not change'
    required: false
    default: 'false'

runs:
  using: "composite"

  steps:
    - name: Set ACTION_REPO
      run: >
        echo "ACTION_REPO=$GITHUB_ACTION_PATH/../../" >> $GITHUB_ENV
      shell: bash

    - name: Set deps-cache-from
      # Don't use cached deps if instructed
      if: ${{ inputs.force_rebuild_deps != 'true' }}
      # For PR commits, use the target branch name as the cache-tag, for other commits, use the branch name itself
      run: echo "FLAG_DEPS_CACHE_FROM=--deps-cache-from=${{ github.repository }}/${{ github.base_ref && github.base_ref || github.ref_name }}" >> $GITHUB_ENV
      shell: bash

    - name: Set deps-cache-to
      # Only write to the cache-tag for non PR commits so PR commits don't upgrade dependency versions
      if: ${{ github.base_ref == '' }}
      run: echo "FLAG_DEPS_CACHE_TO=--deps-cache-to=${{ github.repository }}/${{ github.ref_name }}" >> $GITHUB_ENV
      shell: bash

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    - if: ${{ inputs.python_version != '3.8' }}
      name: Set up Python ${{ inputs.python_version }} for target
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python_version }}

    - run: >
        echo SOURCE_DIRECTORY=$(dirname ${{ inputs.dagster_cloud_file }}) >> $GITHUB_ENV
      shell: bash

    - if: ${{ inputs.deploy == 'true' }}
      run: >
        cd $ACTION_REPO &&
        /usr/bin/python src/deploy_pex.py
        ${{ inputs.dagster_cloud_file }}
        --python-version=${{ inputs.python_version }}
        $FLAG_DEPS_CACHE_TO
        $FLAG_DEPS_CACHE_FROM
      shell: bash

    - if: ${{ inputs.deploy != 'true' }}
      run: >
        cd $ACTION_REPO &&
        generated/gha/dagster-cloud.pex -m dagster_cloud_cli.entrypoint
        serverless build-python-executable
        $SOURCE_DIRECTORY ${{ inputs.build_output_dir }}
        --python-version=${{ inputs.python_version }}
      shell: bash
