name: "Dagster Hybrid Prod Deploy"
description: "Pushes code locations to Dagster Cloud hybrid prod deployment"
inputs:
  organization_id:
    description: "Dagster Cloud organization ID"
    required: true
  dagster_cloud_api_token:
    description: "Dagster Cloud API token"
    required: true
  location:
    required: true
    description: 'The code location to deploy. A JSON string consisting of keys "name", "directory", "registry", "location_file".'
  # Build, push, deploy each location
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Notify build start
      uses: dagster-io/dagster-cloud-action/actions/utils/notify@v0.1
      with:
        organization_id: ${{ inputs.organization_id }}
        action: "pending"
        pr: "${{ github.event.number }}"
        location: ${{ inputs.location }}
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # See https://github.com/docker/build-push-action/ for more info
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ${{ fromJson(inputs.location).directory }}
        push: true
        tags: "${{ fromJson(inputs.location).registry }}:${{ github.sha }}"
        labels: |
          branch=${{ github.head_ref }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Deploy to Dagster Cloud
      uses: dagster-io/dagster-cloud-action/actions/utils/deploy@v0.1
      id: deploy
      with:
        organization_id: ${{ inputs.organization_id }}
        pr: "${{ github.event.number }}"
        pr_status: "${{ github.event.pull_request.merged && 'merged' || github.event.pull_request.state }}"
        location: ${{ inputs.location }}
        image_tag: ${{ github.sha }}
      env:
        DAGSTER_CLOUD_API_TOKEN: ${{ inputs.dagster_cloud_api_token }}

    # Optional steps, leaves PR comment about build status
    - name: Notify build success
      uses: dagster-io/dagster-cloud-action/actions/utils/notify@v0.1
      with:
        organization_id: ${{ inputs.organization_id }}
        action: "complete"
        pr: "${{ github.event.number }}"
        location: ${{ inputs.location }}
        deployment: ${{ steps.deploy.outputs.deployment }}
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
    - name: Notify build failure
      if: ${{ failure() }}
      uses: dagster-io/dagster-cloud-action/actions/utils/notify@v0.1
      with:
        organization_id: ${{ inputs.organization_id }}
        action: "failed"
        pr: "${{ github.event.number }}"
        location: ${{ inputs.location }}
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
