name: "Prerun checks"
description: "Initialization and checks before running the deploy."
outputs:
  result:
    description: "May be 'skip', to indicate the rest of the workflow should be skipped"
    value: ${{ steps.cleanup-closed-pr.outputs.result || steps.check-deployment-type.outputs.result}}
  closed_branch_deployment:
    description: "If this action closed a branch deployment, this field is set to the branch deployment name."
    value: ${{ steps.cleanup-closed-pr.outputs.closed_branch_deployment }} 

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        # Checking out the commit sha should always work. For closed PRs with deleted branches,
        # this checks out the sha of the merge commit.
        ref: ${{ github.sha }}
        path: prerun_checkout_dir

    - name: Cleanup closed PR
      id: cleanup-closed-pr
      if: ${{ github.event.pull_request.state == 'closed' }}
      # Running `ci branch-deployment` synchronizes the state of this PR with dagster cloud. For
      # closed PRs, this marks the pr_status=closed and attaches the merge commit details. 
      run: >
        echo "::notice title=Closed Pull Request::Marking branch deployment closed for this PR, will skip remaining workflow" &&
        $GITHUB_ACTION_PATH/../../../generated/gha/dagster-cloud.pex -m dagster_cloud_cli.entrypoint ci branch-deployment prerun_checkout_dir > /tmp/closed-branch-deployment.txt &&
        echo "closed_branch_deployment=$(cat /tmp/closed-branch-deployment.txt)" >> $GITHUB_OUTPUT
        echo 'result=skip' >> $GITHUB_OUTPUT
      shell: bash

    - if: ${{ github.event.pull_request.state != 'closed' }}
      id: check-deployment-type
      run: >
        echo 'PR not closed (or not in a PR)' &&
        if [ ${ENABLE_FAST_DEPLOYS:-false} == "true" ]; then echo "result=pex-deploy"; else echo "result=docker-deploy"; fi >> $GITHUB_OUTPUT
      shell: bash

