name: "Build pex files for the project"
description: "Builds source.pex and deps.pex"
inputs:
  dagster_cloud_file:
    description: 'Path to dagster_cloud.yaml'
    required: true
  build_output_dir:
    description: 'Directory to write built files into'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout action repo
      uses: actions/checkout@v3
      with:
        repository: dagster-io/dagster-cloud-action-pex
        path: $GITHUB_WORKSPACE/action-repo

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    - run: generated/gha/builder.pex -m builder.deploy ${{ inputs.dagster_cloud_file }} ${{ inputs.build_output_dir }}
      shell: bash
      working-directory: $GITHUB_WORKSPACE/action-repo

    - run: ls -l ${{ inputs.build_output_dir }}
      shell: bash

    - name: Upload built artifacts
      uses: actions/upload-artifact@v3
      with:
        name: built-artifacts
        path: ${{ inputs.build_output_dir }}/
