name: "Run builder.code_location (for testing)"
description: ""
runs:
  using: "composite"
  steps:
    - name: Checkout action repo
      uses: actions/checkout@v3
      with:
        repository: dagster-io/dagster-cloud-action-pex
        path: $GITHUB_WORKSPACE/action-repo

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    - run: generated/gha/builder.pex -m builder.code_location
      shell: bash
      working-directory: $GITHUB_WORKSPACE/action-repo
