# Builds generated/gha/dagster-cloud.pex and writes it to /generated

# Use an official manylinux builder (https://github.com/pypa/manylinux#docker-images)
FROM --platform=linux/amd64 quay.io/pypa/manylinux_2_28_x86_64:latest

ENV PATH="/opt/python/cp311-cp311/bin:$PATH"

RUN python3.11 -m pip install typer rich pex

COPY release.py release.py

RUN mkdir -p complete_platforms
COPY complete_platforms/* complete_platforms/

RUN mkdir -p /generated

CMD ["python3.11", "release.py", "build-dagster-cloud-pex"]
