# Builds ghcr.io/daster-io/dagster-manylinux-builder:*

# This docker image contains the PEX builder (builder.pex) and is capable of 
# building source only dependencies (sdists) for Python that work with Dagster Cloud Serverless base
# images.

# To publish a new version:
# echo $GITHUB-PAT | docker login ghcr.io -u USERNAME --password-stdin
# docker build . -f Dockerfile.dagster-manylinux-builder -t ghcr.io/dagster-io/dagster-manylinux-builder:dev
# docker push ghcr.io/dagster-io/dagster-manylinux-builder:dev

# See ./deploy_pex.py for code that uses this image.

# ---

# Use an official manylinux builder (https://github.com/pypa/manylinux#docker-images)
FROM --platform=linux/amd64 quay.io/pypa/manylinux2014_x86_64:latest

# Add all the relevant Python binaries to the PATH
ENV PATH="/opt/python/cp38-cp38/bin:/opt/python/cp37-cp37m/bin:/opt/python/cp39-cp39/bin:/opt/python/cp310-cp310/bin:$PATH"

# Install the PEX builder
COPY . /src
RUN rm -rf /src/pex-builder/build  # remove any temp build output of working directory

WORKDIR /src/pex-builder
RUN python3 setup.py build
RUN pip3 install pipenv pex
RUN pipenv requirements --exclude-markers > build/lib/requirements.txt
RUN pex -r build/lib/requirements.txt -D build/lib -o /builder.pex -v --include-tools  --python=python3.8 --platform=current

# Run a selftest to ensure it works and also unpack the pex for faster startup
RUN /builder.pex -m builder.selftest

ENTRYPOINT /builder.pex
