name: Hybrid Prod Deploy
on:
  push:
    branches:
      - "main"
env:
  DAGSTER_CLOUD_URL: ${{ secrets.DAGSTER_CLOUD_HYBRID_URL }}
  DAGSTER_CLOUD_API_TOKEN: ${{ secrets.DAGSTER_CLOUD_HYBRID_API_TOKEN }}

jobs:
  parse_workspace:
    runs-on: ubuntu-latest
    outputs:
      build_info: ${{ steps.parse-workspace.outputs.build_info }}
    steps:
      - uses: actions/checkout@v3
      - name: Parse cloud workspace
        id: parse-workspace
        uses: ./actions/utils/parse_workspace
        with:
          dagster_cloud_file: test/dagster_cloud.yaml

  dagster_cloud_build_push:
    runs-on: ubuntu-latest
    needs: parse_workspace
    name: Dagster Hybrid Deploy
    strategy:
      fail-fast: false
      matrix:
        location: ${{ fromJSON(needs.parse_workspace.outputs.build_info) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and deploy to Dagster Cloud hybrid
        uses: ./actions/hybrid_prod_deploy
        with:
          dagster_cloud_api_token: ${{ secrets.DAGSTER_CLOUD_HYBRID_API_TOKEN }}
          location: ${{ toJson(matrix.location) }}
          env_vars: ${{ toJson(secrets) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
