name: Tests PEX CLI and action utils
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test_pex_cli_on_ubuntu:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
      max-parallel: 2
    runs-on: {{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Print dg version
        uses: ./actions/utils/dg-cli
        with:
          command: "--version"

      - name: Print dagster-cloud version
        uses: ./actions/utils/dagster-cloud-cli
        with:
          command: "--version"
