name: Serverless Job Launch (Definitions)
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
env:
  DAGSTER_CLOUD_URL: "https://dagster-cloud-action-github-workflow-serverless.dagster.cloud"

jobs:
  dagster_cloud_launch:
    runs-on: ubuntu-latest
    name: Dagster Serverless Job Launch
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
      - name: Launch a job on Dagster Cloud serverless
        uses: ./actions/utils/run
        with:
          location_name: from_gh_action
          job_name: simple_job
        env:
          DAGSTER_CLOUD_API_TOKEN: ${{ secrets.DAGSTER_CLOUD_SERVERLESS_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
