name: Serverless Prod Deploy
on:
  push:
    branches:
      - "main"
env:
  DAGSTER_CLOUD_URL: ${{ secrets.DAGSTER_CLOUD_SERVERLESS_URL }}
  DAGSTER_CLOUD_API_TOKEN: ${{ secrets.DAGSTER_CLOUD_SERVERLESS_API_TOKEN }}

jobs:
  parse_workspace:
    runs-on: ubuntu-latest
    outputs:
      build_info: ${{ steps.parse-workspace.outputs.build_info }}
    steps:
      - uses: actions/checkout@v4
      - name: Parse cloud workspace
        id: parse-workspace
        uses: ./actions/utils/parse_workspace
        with:
          dagster_cloud_file: sample-repo/dagster_cloud.yaml

  dagster_cloud_build_push:
    runs-on: ubuntu-latest
    needs: parse_workspace
    name: Dagster Serverless Deploy
    strategy:
      fail-fast: false
      matrix:
        location: ${{ fromJSON(needs.parse_workspace.outputs.build_info) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Build and deploy to Dagster Cloud serverless
        uses: ./actions/serverless_prod_deploy
        with:
          dagster_cloud_api_token: ${{ secrets.DAGSTER_CLOUD_SERVERLESS_API_TOKEN }}
          location: ${{ toJson(matrix.location) }}
          env_vars: ${{ toJson(secrets) }}
          base_image: "ghcr.io/dagster-io/dagster-cloud-action:test_custom_base_image"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
