name: "Dagster Hybrid Prod Deploy"
description: "Pushes code locations to Dagster Cloud hybrid prod deployment"
inputs:
  organization_id:
    description: "Dagster Cloud organization ID"
    required: true
  dagster_cloud_api_token:
    description: "Dagster Cloud API token"
    required: true
  location:
    required: true
    description: 'The code location to deploy. A JSON string consisting of keys "name", "directory", "registry", "location_file".'

  deployment:
    required: false
    description: "The deployment to push to, defaults to 'prod'."
    default: "prod"
  checkout_repo:
    required: false
    description: "Whether to start the action by checking out the repository. Set to false if your workflow modifies the file structure before deploying."
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Checkout target repo
      if: inputs.checkout_repo == 'true'
      uses: actions/checkout@v3
      with:
        ref: ${{ github.sha }}

    - name: Checkout action repo
      uses: actions/checkout@v3
      with:
        repository: dagster-io/dagster-cloud-action
        ref: ${{ env.DAGSTER_ACTION_REF }}
        path: ./action-repo/
      env:
        # We need to make sure we are grabbing the right ref for both external invocation of the
        # actions (std) as well as internal invocations of the actions (internal tests).
        # We need to get the local action ref, but this is available in the evaluation of `env`, not
        # during the run time evaluation or the parameter evaluation:
        # https://github.com/orgs/community/discussions/25283
        DAGSTER_ACTION_REF: ${{ github.repository != 'dagster-io/dagster-cloud-action' && github.action_ref || github.head_ref }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        ssh: ${{ env.DOCKER_BUILD_SSH }}
        context: ${{ fromJson(inputs.location).directory }}
        push: true
        tags: "${{ fromJson(inputs.location).registry }}:${{ github.sha }}"
        labels: |
          branch=${{ github.head_ref }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Deploy to Dagster Cloud
      uses: ./action-repo/actions/utils/deploy
      id: deploy
      with:
        organization_id: ${{ inputs.organization_id }}
        deployment: ${{ inputs.deployment }}
        pr: "${{ github.event.number }}"
        location: ${{ inputs.location }}
        image_tag: ${{ github.sha }}
      env:
        DAGSTER_CLOUD_API_TOKEN: ${{ inputs.dagster_cloud_api_token }}
